---

- hosts: revspace
  become: true
  user: root
  roles:
    - { role: "common", tags: [ "common" ] }
    - { role: "dehydrated", tags: [ "dehydrated" ] }
    - { role: "unattended_upgrade", tags: [ "unattended_upgrade" ] }

- hosts: memberservers
  become: true
  user: root
  roles:
    - { role: "ldapclient", tags: [ "ldapclient" ] }

- hosts: ldap.space.revspace.nl
  become: true
  user: root
  roles:
    - { role: "ldapserver", tags: [ "ldapserver" ] }

- hosts: icinga.space.revspace.nl
  become: true
  user: root
  roles:
    - { role: "dehydrated", tags: [ "dehydrated" ] }
    - { role: "icinga", tags: [ "icinga" ] }

- hosts: gateway.space.revspace.nl
  become: true
  user: root
  check_mode: true
  roles:
    - { role: "nameserver", tags: [ "nameserver" ] }

