---

- name: Install bind9
  apt:
    state: latest
    pkg:
      - bind9
      - bind9-host
      - bind9utils
  tags:
    - dns

- name: Create directory for zone files
  file:
    path: /etc/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: 0750

- name: Template zone files
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{item.owner|default('bind')}}"
    group: "{{item.group|default('bind')}}"
    mode: "{{item.mode|default('0644')}}"
    force: "{{item.force|default('yes')}}"
    backup: true
  with_items:
    - { src: "named.conf.local.j2", dest: "/etc/bind/named.conf.local", mode: "0644" }
    - { src: "named.conf.options.j2", dest: "/etc/bind/named.conf.options", mode: "0644" }
    - { src: "dns-zone-space.j2", dest: "/etc/bind/zones/db.space.revspace.nl", mode: "0644" }
  tags:
    - dns
  notify:
    - reload bind9

- name: Make sure bind is started and enabled
  service:
    name: bind9
    state: started
    enabled: true
  tags:
    - dns
