# Install and configure ntpd

---

- hosts: all
  gather_facts: yes
  vars:
   - exploit: bash-exploit.sh
   - output: /tmp/echo
  become: no
  tasks:

  - file: dest={{ output }} state=absent

  - name: Copy exploit-test
    copy: src=files/{{ exploit }} dest=/tmp/{{ exploit }} mode=0755

  - name: Run exploit-test
    shell: chdir=/tmp/ creates={{ output }} /tmp/{{ exploit }}
    ignore_errors: yes
    register: result1

  - name: Check vulnerability status
    debug: msg="Not vulnerable"
    when: 'not( result1.stdout | match("uid=") )'

  - name: Upgrade bash when vulnerable
    apt: name=bash state=latest update_cache=yes
    when: "ansible_os_family == 'Debian' and result1.stdout|match('uid=')"

  - name: Upgrade bash when vulnerable
    yum: name=bash state=latest
    when: "ansible_os_family == 'RedHat' and result.stdout|match('uid=')"

  - file: dest={{ output }} state=absent

  - name: Run exploit-test again
    shell: chdir=/tmp/ creates={{ output }} /tmp/{{ exploit }}
    ignore_errors: yes
    register: result2

  - file: dest={{ item }} state=absent
    with_items:
      - "/tmp/{{ exploit }}"
      - "{{ output }}"

  - name: Fail when still vulnerable
    fail: msg="Still vulnerable"
    when: "result1.stdout | match('uid=') and result2.stdout | match('uid=')"

