# Installation instructions before ansible will work for openwrt/gl-inet devices
#
# Allow root-logins with certificate
#

- hosts: glinet
  gather_facts: no
  vars:
  become: no
  user: root
  tasks:

  - name: Update opkg indexes
    raw: /bin/opkg update

  - name: Install sftp server
    raw: /bin/opkg install openssh-sftp-server

  - name: Install python
    raw: /bin/opkg install python python-json

  - name: Update opkg indexes
    command: /bin/opkg update

  - name: Install required base packages
    opkg: name={{item}} state=installed
    with_items:
      - shadow-groupadd
      - shadow-useradd
      - shadow-groupmod
      - shadow-usermod
      - net-tools-hostname

  - name: Create /home
    file: dest=/home state=directory owner=root group=root mode=0755

  - name: Install authorized-keys
    authorized_key: user=root key="{{item}}" path=/etc/dropbear/authorized_keys
    with_items: rootpubkeys


  - name: Set hostname (permanent)
    lineinfile: 'dest=/etc/config/system line="	option hostname {{inventory_hostname_short}}" regexp="option hostname" insertafter="config system"'
    notify: Set hostname

  handlers:
  - name: Set hostname
    command: hostname {{ inventory_hostname_short }}
