# Installation instructions before ansible will work for openwrt/gl-inet devices
#
# Allow root-logins with certificate
#

- hosts: ldap
  gather_facts: yes
  vars:
  become: no
  user: root 
  roles: 
    - dehydrated
    - ldapserver
    - radiusserver
